import { Component, ElementRef, ViewChild } from '@angular/core';
import { HeaderComponent } from '../../shared/header/header.component';
import { FooterComponent } from '../../shared/footer/footer.component';
import { CommonModule } from '@angular/common';

const ALLOWED_FILE_TYPES = [
  'video/mp4',
  'video/webm',
  'video/ogg',
];

@Component({
  selector: 'app-landing-page',
  imports: [HeaderComponent,FooterComponent,CommonModule],
  templateUrl: './landing-page.component.html',
  styleUrl: './landing-page.component.scss'
})
export class LandingPageComponent {

  @ViewChild('fileInput', { static: false }) fileInput!: ElementRef;

  constructor(){
    
  }

  selected: number | null = 0;

  allowedFileTypes = ALLOWED_FILE_TYPES;

  isUploading = false;
  fileUrl!: string | null;
  uploadFile!: File | null;
  muted:boolean = true;

  data = [
    {
      header: "What is a subtitle generator?",
      content:
        "AI subtitle generators are highly accurate, especially for clear audio and common languages. However, background noise, accents, or technical jargon may require minor manual adjustments.",
    },
    {
      header: "How accurate are AI subtitle generators?",
      content:
        "AI subtitle generators are accurate with clear audio but may struggle with accents, jargon, or noisy input. Manual review is often needed for professional-quality results.",
    },
    {
      header: "Why should I use a subtitle generator for my videos?",
      content:
        "Subtitle generators improve accessibility for all viewers and boost engagement by clarifying speech. They also enhance SEO, helping your videos reach a broader audience.",
    },
    {
      header: "Can I edit the subtitles generated by AI?",
      content:
        "Yes, most AI subtitle tools allow you to edit the generated subtitles. This helps refine accuracy, adjust timing, and ensure the text aligns perfectly with your video content.",
    },
    {
      header: "Does adding subtitles improve video engagement?",
      content:
        "Yes, adding subtitles significantly improves video engagement by making content accessible to a wider audience, including those watching without sound. Subtitles also help viewers retain information and stay focused longer.",
    },
  ];

  toggle(index: number) {
    this.selected = this.selected === index ? null : index;
  }

  toggleForVideoMute(){
    console.log("I am Working")
    if(this.muted != true){
      this.muted = true;
    } else {
      this.muted = false;
    }
  }

  handleChange(event: any) {
    const file = event.target.files[0] as File;
    this.fileUrl = URL.createObjectURL(file);
    this.uploadFile = file;
    console.log(file);

  }

  handleRemovesFile() {
    if (this.fileInput && this.fileInput.nativeElement) {
      this.fileInput.nativeElement.value = null;
    }

    this.uploadFile = null;
    this.fileUrl = null;
  }

  handleUploadFile() {
    // logic to upload file
  }

}
